name: $(Date:yy).$(Date:MM).$(Date:dd).$(Rev:rr)

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  displayName: Install .NET
  inputs:
    packageType: 'sdk'
    version: '9.0.x'
- task: Assembly-Info-NetCore@3
  displayName: Set AssemblyInfo
  inputs:
    Path: '$(Build.SourcesDirectory)'
    FileNames: |
      src/Disco.Core/Disco.Core.csproj
      src/Disco.Remote/Disco.Remote.csproj
    InsertAttributes: false
    FileEncoding: 'auto'
    WriteBOM: false
    PackageId: 'Disco.Core'
    VersionNumber: '$(Build.BuildNumber)'
    FileVersionNumber: '$(Build.BuildNumber)'
    InformationalVersion: '$(Build.BuildNumber)'
    PackageVersion: '$(Build.BuildNumber)'
    LogLevel: 'verbose'
    FailOnWarning: false
    DisableTelemetry: true
- task: DotNetCoreCLI@2
  displayName: Restore Projects
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    vstsFeed: 'e6d52dbd-ece6-4c79-949c-1ee577f0eb25'
- task: DotNetCoreCLI@2
  displayName: Build Projects
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '-c Release'
- task: DotNetCoreCLI@2
  displayName: Pack Nuget Packages
  inputs:
    command: 'pack'
    packagesToPack: './src/Disco.Core/Disco.Core.csproj'
    includesymbols: true
    includesource: true
    versioningScheme: 'byBuildNumber'
- task: DotNetCoreCLI@2
  displayName: Pack Nuget Packages
  inputs:
    command: 'pack'
    packagesToPack: './src/Disco.Remote/Disco.Remote.csproj'
    includesymbols: true
    includesource: true
    versioningScheme: 'byBuildNumber'
- task: DotNetCoreCLI@2
  displayName: Publish Nuget Packages
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'e6d52dbd-ece6-4c79-949c-1ee577f0eb25'

- task: PowerShell@2
  displayName: Building Disco.Server Container
  inputs:
    filePath: './Create.ps1'